### ISSUE TITLE
Version for Versa

### ISSUE THREAD

**Issue by laurawingx** [ViGouRCanberra/ionic-watchface-borderlands#4]
Hi I played Borderlands.. love this clock face. I'm VERY new to this development and was wondering if you modified for Versa. I've been able to move everything down, but the progress bars are all messed up. I'm trying to learn how to do graphical progress bars. Learning a lot from your code. Cheers.

**Comment by ViGouRCanberra** [comment]
Hey @laurawingx, If haven't ported this for the Versa sadly because I don't have one and there's no emulator to test on yet.
If you however have any issues, feel free to ask me on here, or create a Github repository for your project and I'll gladly assist there.
