### ISSUE TITLE
Fitbit Versa compatibility

### ISSUE THREAD

**Issue by ViGouRCanberra** [ViGouRCanberra/ionic-watchface-borderlands#5]
Currently this watchface only works on the Fitbit Ionic. Make the watchface compatible with the Fitbit Versa

**Comment by Crocibearamoose** [comment]
Any plans to convert this and make it usable on Versa3?

**Comment by ViGouRCanberra** [comment]
None sadly. My Fitbit Ionic was recalled recently, and I'm no longer working on this on this.
